name: Build Windows Installer
on:
  workflow_dispatch: # Allows you to manually trigger the build with a single click

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Install dependencies
        run: npm install

      - name: Build Electron Executable
        run: |
          if (Select-String -Path package.json -Pattern '"package"') { npm run package }
          elseif (Select-String -Path package.json -Pattern '"build"') { npm run build }
          elseif (Select-String -Path package.json -Pattern '"dist"') { npm run dist }
          else { npm run package }
        shell: powershell

      - name: Upload Installer Executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-app-installer
          path: |
            dist/**/*.exe
            out/**/*.exe
